services:
  - type: web
    name: fintrackr-backend
    runtime: docker
    plan: free
    autoDeploy: true
    healthCheckPath: /actuator/health
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: PORT
        value: 10000
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        value: 3306
      - key: DB_NAME
        sync: false
      - key: USE_SSL
        value: true
      - key: DB_USERNAME
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: JWT_EXPIRATION
        value: 86400000
      - key: APP_FRONTEND_RESET_PASSWORD_URL
        sync: false
      - key: APP_FRONTEND_VERIFY_EMAIL_URL
        sync: false
      - key: MAIL_HOST
        value: smtp.gmail.com
      - key: MAIL_PORT
        value: 587
      - key: MAIL_USERNAME
        sync: false
      - key: MAIL_PASSWORD
        sync: false
      - key: MAIL_FROM
        sync: false
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
      - key: APP_ENCRYPTION_SECRET_KEY
        sync: false
      - key: APP_RECOMMENDATION_BASE_URL
        sync: false
      - key: APP_RECOMMENDATION_API_KEY
        sync: false
      - key: CURRENCY_API_URL
        value: https://open.er-api.com/v6/latest/INR
      - key: CURRENCY_FETCH_RATE_MS
        value: 60000
